name: Frontend - Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/front.yml'
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  # Defaults seguros; si tienes repo variables/secret, las puedes sobreescribir.
  S3_BUCKET: ${{ vars.S3_BUCKET || 'mozart-cemdi-front' }}
  CF_DIST_ID: ${{ vars.CF_DIST_ID || 'E35WF807SY6L8M' }}
  NODE_VERSION: '20'
  API_URL: ${{ vars.API_URL || 'http://mozart-cemdi-alb-894060528.us-east-1.elb.amazonaws.com' }}

concurrency:
  group: front-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install
        working-directory: apps/frontend
        run: npm ci

      - name: Build (Vite)
        working-directory: apps/frontend
        env:
          # Prioriza secret si existe; si no, usa el ALB del env.
          VITE_API_URL: ${{ secrets.VITE_API_URL || env.API_URL }}
        run: npm run build

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_FRONT_ARN || 'arn:aws:iam::534039229473:role/mozart-cemdi-gha-role' }}

      - name: Upload to S3
        run: aws s3 sync apps/frontend/dist "s3://${{ env.S3_BUCKET }}" --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CF_DIST_ID }} --paths "/*"
